### ISSUE TITLE
Add meta tag for mobile scalability 

### ISSUE THREAD

**Issue by HJBowers** [nkj76/splurty1#1]
Adding a meta tag (`<meta name="viewport" content="width=device-width, initial-scale=1">`) in your `app/views/layouts/application.html.erb` file will allow it to scale better on a mobile device.

**Comment by nkj76** [comment]
Finally made this change to add the meta tag. Did it in both the splurty and nomster apps.
And yes, it makes a big difference, the mobile rendering is much better - larger characters, fill up the screen. It becomes obvious that now it's aware of the screen size.
Thanks for the tip!
(Should I be posting the diff here or something like that??)
